version: 0.2
phases:
  install:
    runtime-versions:
      nodejs: 12
  pre_build:
    commands:
      - apt-get update -y
  build:
    commands:
      - cd $CODEBUILD_SRC_DIR
      - mkdir node_modules
      - npm install sharp
      - cd node_modules
      - ls -lh

artifacts:
  files:
    - './cf-template/**/*'
    - './learningpool/**/*'
    - './pipeline-template/**/*'
    - './build/target/**/*'