version: 0.2
phases:
  install:
    runtime-versions:
      nodejs: 12
  pre_build:
    commands:
      - apt-get update -y
  build:
    commands:
      - cd learningpool
      - mkdir node_modules
      - npm install sharp
      - cd node_modules
      - cd ..
      - ls -lh
      - zip -r learningpool.zip
      - aws lambda update-function-code --function-name learningpool --zip-file fileb://learningpool.zip

artifacts:
  files:
    - './cf-template/**/*'
    - './learningpool/**/*'
    - './pipeline-template/**/*'