AWSTemplateFormatVersion: "2010-09-09"
Description: "Lambda function"
Parameters:
    SourceBucket:
        Type: String
        Default: lambdatestmw
    ResizerBucket:
        Type: String
        Default: mwresizerbucket

Resources:
    LambdaS3ExecutionRole:
        Type: AWS::IAM::Role
        Properties:
            RoleName: "LambdaS3ExecutionRole"
            AssumeRolePolicyDocument:
                Version: '2012-10-17'
                Statement:
                    - Effect: Allow
                      Principal:
                          Service:
                              - lambda.amazonaws.com
                      Action:
                          - sts:AssumeRole
            Path: "/"
            Policies:
                - PolicyName: LambdaS3ExecutionRole
                  PolicyDocument:
                      Version: '2012-10-17'
                      Statement:
                          - Action:
                                - logs:*
                                - iam:*
                                - s3:*
                            Effect: Allow
                            Resource: '*'

    ImageResizer:
        Type: AWS::Lambda::Function
        Properties:
            FunctionName: ImageResizer
            Role: !GetAtt LambdaS3ExecutionRole.Arn
            Runtime: "nodejs12.x"
            Handler: index.handler
            Code:
                S3Bucket: !Ref 'SourceBucket'
                S3Key: !Sub 'learningpool.zip'

    UploadBucket:
      Type: AWS::S3::Bucket
      DependsOn: ProcessingLambdaPermission
      Properties:
        BucketName: !Ref ResizerBucket
        NotificationConfiguration:
          LambdaConfigurations:
            - Event: "s3:ObjectCreated:Put"
              Function: !GetAtt ImageResizer.Arn

    ProcessingLambdaPermission:
      Type: AWS::Lambda::Permission
      Properties:
        Action: 'lambda:InvokeFunction'
        FunctionName: !Ref ImageResizer
        Principal: s3.amazonaws.com
        SourceArn: !Sub 'arn:aws:s3:::${ResizerBucket}'
        SourceAccount: !Ref AWS::AccountId

    ResizedBucket:
        DependsOn: UploadBucket
        Type: AWS::S3::Bucket
        Properties:
            BucketName: !Sub ${ResizerBucket}-resized
